version: '2'
services:
  db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: alnitek82
      MYSQL_USER: root
      MYSQL_PASSWORD: alnitek82
      MYSQL_DATABASE: myshop
  web:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8086:80
    volumes:
      - /sessions  